name: Build Image and Push it to Docker Hub
on:
  push:
    branches:
      - master
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2   
        with:
          fetch-depth: 0  
      - name: Git Version
        uses: codacy/git-version@2.5.4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          images: |
            ${{ secrets.DOCKER_REPOSITORY }}
          tags: |
            latest
            ${{ steps.gitversion.outputs.major }}
            ${{ steps.gitversion.outputs.major }}.${{ steps.gitversion.outputs.minor }}
            ${{ steps.gitversion.outputs.major }}.${{ steps.gitversion.outputs.minor }}.${{ steps.gitversion.outputs.patch }}